### ISSUE TITLE
No structures.pk

### ISSUE THREAD

**Issue by ferdianjovan** [rgrosse/compositional_structure_search#2]
Hi, I tried to run the example. When I ran

```
python experiments.py everything example
```

That gives me an error as follows

```
IOError: [Errno 2] No such file or directory: 'results\\example\\level1\\structu
res.pk'
```

Any idea what I did wrong?

cheers

**Comment by rgrosse** [comment]
Hi Ferdian,

Can you be more specific about which line causes the error?

Roger

**Comment by ferdianjovan** [comment]
Hi Grosse,

Everything works fine on Linux now. I was running it on Windows environment when I bumped into the problem before.
Thanks for the reply.
